microsoft/mu_rust_pi

- cspell.json
- src/fw_fs.rs
- src/fw_fs/ffs.rs
- src/fw_fs/ffs/file.rs
- src/fw_fs/ffs/guid.rs
- src/fw_fs/ffs/section.rs
- src/fw_fs/fv.rs
- test_resources/GIGANTOR_expected_values.yml
This is a refactor of the FFS support to add support for large files/sections (i.e. EFI_FIRMWARE_FILESYSTEM_3). The previous implementation only supported small (less than 16MB) files/sections (i.e. EFI_FIRMWARE_FILESYSTEM_2). 
- Adds support for FFS 3.
- Significant refactor of API for accessing FFS objects.
- Added tests to verify FFS 3 large files.
- updated rustdocs
Unit tests pass. 
Consumers of the affected modules will need to update to use the new APIs.
> FFS refactor to add support for large files/sections

- Cargo.toml
- src/fw_fs/ffs/file.rs
* Cargo.toml:
* Add nightly feature to supress unexpected_cfgs warning
* change 'default_features' to 'default-features' as the new convention is required for Rust 2024 edition
* files.rs:
* Add allow(dead_code) for the Header2 struct to supress dead_code warning.
For details on how to complete to complete these options and their meaning refer to [CONTRIBUTING.md](https://github.com/microsoft/mu/blob/HEAD/CONTRIBUTING.md).
* All warnings were properly supressed.
* Verified these changes are compatibley with Rust toolchain 1.76.
N/A
> Fix warnings generated when compiling with rust toolchain 1.80

- src/hob.rs
Adds a definition for `MEMORY_TYPE_INFO_HOB_GUID` and related structure.
Adds support for a new struct.
Standard rust docs
Verified new structure definition locally.
N/A
> Add MemoryTypeInfo HOB definitions

- src/fw_fs.rs
- src/fw_fs/ffs/section.rs
* Add a test for section metadata correctness
* fix a bug in GUID_DEFINED section parsing.
- bugfix
Added unit test to verify SectionMetadata correctness.
N/A
> Adds a test for SectionMetadata parsing and fixes an issue with GUID_DEFINED section parsing.

- src/boot_mode.rs
- src/hob.rs
- src/lib.rs
1. Make the boot mode an enum so it can be extended with methods and other functionality over time.
2. Move the boot mode out of the `hob` module. While the boot mode is delivered in the Phase Handoff Information Table (PHIT) HOB, it is an independent concept of the HOB.
3. Add a `Display` implementation so the boot mode can be printed in more human readable form. Example:
`Boot Assuming No Configuration Changes (0x2)`
4. Drop `Efi` from the type name since this is a PI Spec concept and the `Efi` prefix is confusing (though used in edk2 C code).
5. Add documentation.
- Mu Rust PI build, clippy, fmt, and test
- Verify output on a Rust platform that dumps that PHIT HOB in a print that uses the `BootMode` Display trait:
```
INFO - PHASE HANDOFF INFORMATION TABLE (PHIT) HOB
HOB Length: 0x38 …
```
> Refactor Boot Mode

- Cargo.toml
- src/fw_fs.rs
Validate the firmware volume header by checking the signature, before the call to `core::slice::from_raw_parts`. This is because if the passed address is not a firmware volume, the call to `from_raw_parts` could panic, instead of catching the failure later and cleanly returning an error.
This validation typically takes place in the `new` function. It will continue to take place there, but it also needs to be validated here to prevent a panic with the `from_raw_parts` call.
Failing tests now pass
N/A
> fw_fs: new_from_address: add validation of firmware volume header

- src/protocols.rs
- src/protocols/security.rs
- src/protocols/security2.rs
Add support for spec protocol definitions for Security and Security2 Architectural protocols as described in section 12.9 of the PI specification (https://uefi.org/specs/PI/1.8A/V2_DXE_Architectural_Protocols.html#security-architectural-protocols)
Confirmed that the defined structures build.
N/A
> Add spec protocol definitions for Security and Security2 Protocols as defined in PI spec

- src/status_code.rs
Re-align with latest changes from mu_basecore repo in PiStatusCode.h
N/A
N/A
> status_code: Remove custom status codes to align with mu_basecore

- src/protocols/cpu_arch.rs
Switches from using a cvoid to using the `EFI_SYSTEM_CONTEXT` from the `EFI_DEBUG_SUPPORT_PROTOCOL` defined in r-efi. This is the definition specified in the PI spec.
N/A
N/A
> Use r-efi definition for EfiSystemContext per the PI spec

- src/hob.rs
HobList is just a wrapper around a Vec<Hob>. Since Vec::new() is const, HobList::new() can be const as well, allowing for an empty HobList to be present in a struct that exists before allocations are available.
This continues to compile.
N/A
> hob: Make HobList::new() const

- src/hob.rs
Adds an implementation of `IntoIterator` for `&HobList`, which allows us to iterate over the list of hobs without consuming the list itself.
Added additional tests to ensure we can continue to iterate over `HobList` (which consumes HobList), but also iterate over `&HobList`.
N/A
> hob: add IntoIterator for &HobList

- src/hob.rs
This change adds the implementation of supporting "resource descriptor hob type 2", which will extends the existing definition of resource descriptor hob with an attribute field.
This field can be used to provide the actual attributes needs to be set for the memory region, instead of relying on the state of the system.
This was tested on QEMU SBSA and Q35, both booted to Windows.
N/A
> Adding resource descriptor hob type 2

- Cargo.toml
- src/hob.rs
- Fix GuidHob data not copied in new memory when relocating hobs. 
- Reusing the same array but only changing the reference to the hob in the array.
I booted to shell in qemu with this version and the guid hobs that contain PEI records had data in them.
N/A
> Fix GuidHob bug and rework relocate_hobs.

- src/hob.rs
This example makes assumptions that are not valid for actual execution as a doctest and it results in this hang when run:
"test src\hob.rs - hob::get_c_hob_list_size (line 726) has been running for over 60 seconds"
- `cargo make test`
N/A
> hob: Do not run get_c_hob_list_size() example

- src/fw_fs.rs
A few warnings appear running `cargo doc` due to broken links. This fixes those so `cargo doc` output is clean.
- `cargo doc`
N/A
> fw_fs: Fix broken intra cargo doc links

- cspell.json
- src/protocols.rs
- src/protocols/communication.rs
- src/protocols/communication2.rs
- src/protocols/communication3.rs
Closes #49 
Adds protocol definitions for:
- EFI_MM_COMMUNICATION_PROTOCOL
- EFI_MM_COMMUNICATION2_PROTOCOL
- EFI_MM_COMMUNICATION3_PROTOCOL
These provide a means of communicating between drivers outside of MM and MMI handlers inside of MM.
- `cargo build`, `cargo doc`, `cargo test`, `cargo fmt`, `cargo clippy`
N/A - Normal protocol usage as needed.
> protocols: Add MM Communication protocols

- rust-toolchain.toml
cargo-release was removed during a file sync in de71243. It needs to be added back so the publish release workflow can download cargo-release.
- GitHub workflow on fork
- N/A
> rust-toolchain.toml: Add cargo-release

- cspell.json
- examples/brotli.rs
- src/fw_fs.rs
Add common GUIDs used for compression in PI firmware so they are shared across implementations.
- Cargo build, check, test
- Update any existing definitions to use these
> Add compression section GUIDs

- src/hob.rs
Pretty print the GUID to make the HOB log info more useful.
Before:
```
GUID HOB
HOB Length: 0xbb8
```
After:
```
GUID HOB
Type: 0x4
Length: 0xbb8,
GUID: {3b387bfd-7abc-4cf2-a0ca-b6a16c1b1b25}
```
- HOB dump in QEMU boot
N/A
> Print the GUID for GUID HOBs

- src/hob.rs
* Update the Capsule structure to properly align with the UEFI specification.
* https://uefi.org/specs/PI/1.8A/V3_HOB_Code_Definitions.html#uefi-capsule-hob
* Add Hob Type print to alignment panic for easier debug.
* Verified that the size comparision of a UEFI_CAPSULE hob no longer panics when casting the hob pointer.
N/A
> Align Capsule structure with UEFI_CAPSULE HOB structure definition

- src/fw_fs/ffs/file.rs
- src/fw_fs/fv.rs
- src/hob.rs
Make PI spec structures for FFS public from `pub crate`.
Also includes a minor lint fix for HOB iter() API lifetime specification. 
Passes unit tests, functional testing on hardware works.
N/A
> Make FFS spec members public.
